name: 'Validate NPM Package Version'
description: 'Ensure that the package version you want to publish is available'
outputs:
  result:
    description: "Indicates whether the version check is considered success or failure"
    value: ${{ steps.version-check.outputs.result }}
  version:
    description: "The version number found in the package.json"
    value: ${{ steps.version-check.outputs.version }}
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v1
      with:
        always-auth: true
        node-version: 16.x
        registry-url: https://npm.pkg.github.com
        scope: '@icanbwell'
    - id: version-check
      run: entrypoint.sh
      shell: sh
    - if: ${{steps.version-check.outputs.result == 'failure'}}
      run: echo "The git tag v${{ steps.version-check.outputs.version }} already exists.  Did You forget to increment the version number in package.json?"; exit 1
      shell: sh

